#server.port=0
server.port=5050
spring.application.name=DUMMY-ENDPOINTS
moviedb.api.key = cea3b7a0b210db1ea9f3707365849dd8
#moviedb.url = https://api.themoviedb.org/3/movie/latest?api_key=${moviedb.api.key}&language=en-US
empleado.url =	https://dummy.restapiexample.com/api/v1/employee/1
eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true